"""phone code and phone no alter to the user table

Revision ID: 1d56edc9b2ae
Revises: c8cef5241d72
Create Date: 2026-01-27 15:42:57.941270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d56edc9b2ae'
down_revision: Union[str, None] = 'c8cef5241d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('users', 'phonenumber',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phonenumber',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('users', 'phone_code',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
