"""pancard added to the user table

Revision ID: 59c7e6305636
Revises: a5595839b186
Create Date: 2026-01-27 12:59:17.509807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c7e6305636'
down_revision: Union[str, None] = 'a5595839b186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pancard', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_pancard'), 'users', ['pancard'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_pancard'), table_name='users')
    op.drop_column('users', 'pancard')
    # ### end Alembic commands ###
