"""phone code and phone no added to the user table

Revision ID: c8cef5241d72
Revises: 59c7e6305636
Create Date: 2026-01-27 14:27:05.921599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8cef5241d72'
down_revision: Union[str, None] = '59c7e6305636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_code', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('phonenumber', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_phonenumber'), 'users', ['phonenumber'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phonenumber'), table_name='users')
    op.drop_column('users', 'phonenumber')
    op.drop_column('users', 'phone_code')
    # ### end Alembic commands ###
