"""alter unique columns in the user table

Revision ID: d1a8e23a3a7a
Revises: 909bc30a6a94
Create Date: 2026-01-27 16:16:45.122086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a8e23a3a7a'
down_revision: Union[str, None] = '909bc30a6a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_users_phonenumber'), table_name='users')
    op.create_index(op.f('ix_users_phonenumber'), 'users', ['phonenumber'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phonenumber'), table_name='users')
    op.create_index(op.f('ix_users_phonenumber'), 'users', ['phonenumber'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
